//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDDEntities : DbContext
    {
        public PDDEntities()
            : base("name=PDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<act> act { get; set; }
        public DbSet<item_list_prohibition> item_list_prohibition { get; set; }
        public DbSet<item_list_resolution> item_list_resolution { get; set; }
        public DbSet<road_sign> road_sign { get; set; }
        public DbSet<type_road_sign> type_road_sign { get; set; }
    }
}
