//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_road_sign
    {
        public type_road_sign()
        {
            this.road_sign = new HashSet<road_sign>();
        }
    
        public long code_type_road_sign { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<road_sign> road_sign { get; set; }
    }
}
